get http://localhost:2000/reservations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyNzYzMjAzN30.fBzv0NkWQKJi69Wi1hiagU3kUmaHmPvid1o9SbEXAx4
Content-Type: application/json

