post http://localhost:2000/productDetails
# Authorization: Barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcyNzYxNTg5MH0.Oa_4v_lzeC7vsIXFGDZz9nCX0Pr5XYqwAy0CipnKAm0
# Content-Type: application/json

